language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
sudo: required
dist: trusty
group: deprecated-2019Q2
before_install:
- sudo pip install supervisor
- sudo mkdir -p examples/single/var/log
- sudo mkdir -p examples/single/var/run
- sudo /usr/local/supervisord -c exampels/single/supervisord.conf
script:
- sleep 5 && go test -v 
