language: go
go:
  - 1.11.x
  - 1.12.x
sudo: required
dist: trusty
group: deprecated-2019Q2
before_install:
- sudo pip install --upgrade pip
- sudo pip install supervisor
- mkdir -p examples/single/var/log
- mkdir -p examples/single/var/run
- cd examples/single && /usr/local/bin/supervisord -c supervisord.conf
script:
- GO111MODULE=on go mod download
- sleep 5 && GO111MODULE=on TEST_SUPERVISORD=/usr/local/bin/supervisord TEST_SUPERVISORCTL=/usr/local/bin/supervisorctl go test -v 
