language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
sudo: required
dist: trusty
group: deprecated-2019Q2
before_install:
- sudo pip install --upgrade pip
- pip install supervisor
- mkdir -p examples/single/var/log
- mkdir -p examples/single/var/run
- /usr/bin/supervisord -c exampels/single/supervisord.conf
script:
- sleep 5 && go test -v 
